- icon: excavator3
  title: Maa- ja vesirakennuskoneiden ylläpitoa
  description: Kulutusosien vaihtotyöt, kauhat, kynnet, telastot, kuormalavat, murskainten kulutus, osien vaihdot, kuljettimien kunnosapidot ja huollot.

- icon: barrel4
  title: Vaarallisten aineiden kuljetuksia
  description: Yrityksellä on vaarallisten aineiden kuljetusluvat sekä säiliöissä, että kappaletavarana.

- icon: professor5
  title: Työnjohto- ja konsultointitehtäviä
  description: Lorem ipsum dolor sit amet, consectetur adipisicing elit. 

- icon: teacher4
  title: Koulutusta ja perehdytystä
  description: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quam minima, itaque molestiae ut ratione unde?
