- icon: excavator3
  title: Maa- ja vesirakennuskoneiden ylläpitoa
  description: Kulutusosien vaihtotyöt, kauhat, kynnet, telastot, kuormalavat, murskainten kulutus, osien vaihdot, kuljettimien kunnosapidot ja huollot.

- icon: barrel4
  title: Vaarallisten aineiden kuljetuksia
  description: Yrityksellä on vaarallisten aineiden kuljetusluvat sekä säiliöissä, että kappaletavarana.

- icon: professor5
  title: Työnjohto- ja konsultointitehtäviä
  description: Voimme toimia työnjohto- ja konsultointitehtävissä maarakennus- sekä murskaprojekteissa. Erikoisalueina erityisesti puu, kivi, muovi ja muut murskattavat partikkelit.

- icon: teacher4
  title: Koulutusta ja perehdytystä
  description: Koulutamme ja perehdytämme kaikissa maarakennusalan tehtävissä. Yrityksen toimitusjohtajalla on 26 vuoden kokemus alalta.
