- icon: icon-user-md
  title: Maa- ja vesirakennuskoneiden ylläpitoa
  description: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quam minima, itaque molestiae ut ratione unde?

- icon: icon-diamond
  title: Vaarallisten aineiden kuljetuksia
  description: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quam minima, itaque molestiae ut ratione unde?

- icon: icon-flask
  title: Työnjohto- ja konsultointitehtäviä
  description: Lorem ipsum dolor sit amet, consectetur adipisicing elit. 

- icon: icon-globe
  title: Koulutusta ja perehdytystä
  description: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quam minima, itaque molestiae ut ratione unde?
